language: ruby
bundler_args: --without development
before_install:
- 'echo ''gem: --no-ri --no-rdoc'' > ~/.gemrc'
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - 2.0.0
  # - 2.1.0
  - jruby-18mode
  - jruby-19mode
  - ruby-head
  - jruby-head
  - ree
